# This is a basic workflow to help you get started with Actions

name: WDIO-CI
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: ${{secrets.RUNNER}}
      LOG_LEVEL: ${{secrets.LOG_LEVEL}}
      TEST_NOP_ADMIN_USERNAME: ${{secrets.TEST_NOP_ADMIN_USERNAME}}
      TEST_NOP_ADMIN_PASSWORD: ${{secrets.TEST_NOP_ADMIN_PASSWORD}}
      DEBUG: ${{secrets.DEBUG}}
      HEADLESS: ${{secrets.HEADLESS}}

    steps:
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Running smoke tests
        run: npm run test:smoke